replicaCount: 1

image:
  repository: 986154984217.dkr.ecr.ap-northeast-1.amazonaws.com/container-nodejs-api-8000
  tag: v1.0.0  # バージョン番号を指定
  pullPolicy: Always

service:
  type: NodePort
  port: 8000
  nodePort: 30800   # Kind -> host 8000 にマッピング済

containerPort: 8000

ingress:
  enabled: false
resources: {}

# ServiceAccount設定を追加
serviceAccount:
  create: false
  name: ""
  annotations: {}

# オートスケーリング設定を追加
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
